apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: notes-mysql
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: notes-mysql
  serviceName: notes-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: notes-mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.mysql.image }}
          envFrom:
            - secretRef:
                name: notes-mysql
          ports:
            - containerPort: {{ .Values.mysql.port }}
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.mysql.storage }}
