apiVersion: v1
kind: Service
metadata:
  name: notes-nginx
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: notes-nginx
  ports:
    - port: 80
      targetPort: {{ .Values.nginx.port }}
  type: LoadBalancer
