namespace: notes

# MySQL settings
mysql:
  rootPassword: rootpassword
  database: notesdb
  user: notesuser
  password: notespass
  image: mysql:8.0
  port: 3306
  storage: 1Gi

# Web app settings
web:
  image: 209479261816.dkr.ecr.us-east-1.amazonaws.com/notes-web
  tag: effc534beb3899b5ded7df78bd10ef9fff4c2014
  port: 5000
  replicas: 2
  env:
    FLASK_ENV: "production"
    DB_HOST: "notes-mysql"
    DB_USER: "notesuser"
    DB_PASSWORD: "notespass"
    DB_NAME: "notesdb"
    DB_PORT: "3306"

# Nginx settings
nginx:
  image: nginx:alpine
  port: 80
  replicas: 1
