namespace: notes

# MySQL settings
mysql:
  rootPassword: rootpassword
  database: notesdb
  user: notesuser
  password: notespass
  image: 209479261816.dkr.ecr.us-east-1.amazonaws.com/notes-web
  port: 3306
  storage: 1Gi

# Web app settings
web:
  image: 209479261816.dkr.ecr.us-east-1.amazonaws.com/notes-web
  tag: d525a18cb76f3193c5ba44dc9bb55df513ee7a78
  port: 5000
  replicas: 1
  env:
    FLASK_ENV: "production"
    DB_HOST: "notes-mysql"
    DB_USER: "notesuser"
    DB_PASSWORD: "notespass"
    DB_NAME: "notesdb"
    DB_PORT: "3306"

# Nginx settings
nginx:
  image: nginx:alpine
  port: 80
  replicas: 1
